management:
  endpoints:
    web:
      exposure:
        include: health # 필요한 경우 info, metrics 등 추가
  endpoint:
    health:
      show-details: never # 외부에는 상태 코드만 응답 (보안)

server:
  port: 9001

aws:
  dynamodb:
    region: ap-northeast-2